ProjectMVC/COURSE_CODING/Models/Question.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace COURSE_CODING.Models
{
    public class Question
    {
        [Key]
        public int ID { get; set; }
        public int Score { get; set; }
        public string Description { get; set; }
        public short? Type { get; set; }
        public Answer[] List { get; set; }
    }
}

ProjectMVC/COURSE_CODING/Controllers/ChallengeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net.Http;
using System.Web;
using System.Web.Mvc;
using System.Web.Script.Serialization;
using CommonProject;
using CommonProject.Models;
using COURSE_CODING.Common;
using COURSE_CODING.Models;
using DAO.DAO;
using DAO.EF;
using Newtonsoft.Json;

namespace COURSE_CODING.Controllers
{
    public class ChallengeController : BaseController
    {

        // GET: Challenge
        [Route("Challenge/{challengeID}/Problem")]
        [Route("Compete/{competeID}/Challenge/{challengeID}/Problem")]
        public ActionResult Problem( int challengeID, int? competeID)
        {
            int UserID = this.GetLoginID();

            ChallengeDAO challengeDao = new ChallengeDAO();
            //check is available for user (is public or enter compete
            bool CanAccess = challengeDao.CanAccess(UserID, challengeID, competeID);
            if (!CanAccess)
            {
                ViewBag.CanAccess = CanAccess;
                return View("Problem");
            }

            //Prepare model
            ChallengeModel model = new ChallengeModel();
            //Fill data
            model.challenge = challengeDao.GetOne(challengeID);
            model.OwnerName = (new UserDAO()).GetNameByID(model.challenge.OwnerID);
            model.languages = (new LanguageDAO()).GetByChallengeID(challengeID);

            var cs = (new ChallengeDAO()).GetCodeStubs(challengeID);

            foreach (var item in cs)
            {
                if (item.LanguageID == 1)
                {
                    model.CodeStubs_Cpp = item.CodeStub;
                }
                else if (item.LanguageID == 2)
                {
                    model.CodeStubs_CSharp = item.CodeStub;
                }
                else if (item.LanguageID == 3)
                {
                    model.CodeStubs_Java = item.CodeStub;
                }
            }

            ViewBag.competeID = competeID;
            if(competeID != null)
            {
                ViewBag.Back = challengeDao.GetBackChallenge((int)competeID, challengeID);
                ViewBag.Next = challengeDao.GetNextChallenge((int)competeID, challengeID);
            }
            return View(model);
        }

        [Route("Compete/{id}/Question")]
        public ActionResult Question(int id)
        {
            //Check User permission access to Compete
            CompeteDAO competeDao = new CompeteDAO();
            bool can_access = competeDao.CanAccess(id, this.GetLoginID());
            if (!can_access)
            {
                ViewBag.CanAccess = false;
                return View("Question");
            }

            //Prepare model
            List<QuestionModel> model = new List<QuestionModel>();
            dynamic questions = (new QuestionDAO()).GetAllWithAnswerByCompeteID(id, this.GetLoginID());
            //Fill data
            //var questions = (new QuestionDAO()).GetAllByCompeteID(id);
            foreach (var one_question in questions)
            {
                QuestionModel one = new QuestionModel();
                var question = one_question.GetType().GetProperty("Question").GetValue(one_question, null);
                var chosen   = one_question.GetType().GetProperty("Chosen").GetValue(one_question, null);
                one.title = question.Title;
                one.type = question.Type;
                one.score = question.Score;
                one.answers = JsonConvert.DeserializeObject(question.Choise);
                if (chosen != null)
                {
                    dynamic choised = JsonConvert.DeserializeObject(chosen.Content);
                    foreach (var choise in choised)
                    {
                        one.last_choised.Add(Int32.Parse(choise.Value));
                    }
                }
                model.Add(one);
            }
            ViewBag.competeID = id;
            ViewBag.ContestTile = competeDao.GetOne(id).Title;
            return View("Question", model);
        }

        //Helper Match 2 array
        protected bool isMatchArray(dynamic a, dynamic b)
        {
            if (a.Count != b.Count)
            {
                return false;
            }
            for (int i = 0; i < a.Count; i++)
            {
                if (a[i] != b[i])
                {
                    return false;
                }
            }
            return true;
        }

        [HttpPost]
        [Route("Compete/{id}/Question/Submit")]
        public ActionResult SubmitQuestion(int id)
        {
            string data = Request.Form["answer"];
            dynamic arr_answer = JsonConvert.DeserializeObject(data);
            List<QUESTION> arr_result = (new QuestionDAO()).GetAllByCompeteID(id);

            if (arr_answer.Count != arr_result.Count)
            {
                return Json(new { status = "fail", message = "Questions not match result" });
            }

            int UserID = this.GetLoginID();
            QuestionAnswerDAO DAO = new QuestionAnswerDAO();
            int entity_result = 0;
            for (int i = 0; i < arr_result.Count; i++)
            {
                dynamic one_result = JsonConvert.DeserializeObject(arr_result[i].Result);
                dynamic one_answer = arr_answer[i];
                if (this.isMatchArray(one_result, one_answer))
                {
                    entity_result = 1;
                }

                QUESTION_ANSWER entity = new QUESTION_ANSWER();
                entity.UserId = UserID;
                entity.TimeDone = DateTime.Now;
                entity.QuestionID = arr_result[i].ID;
                entity.Content = JsonConvert.SerializeObject(arr_answer[i]);
                entity.Result = entity_result;
                bool insert_result = DAO.InsertOrUpdate(entity);
            }
            return Json(data);
        }

        protected int GetLoginID()
        {
            var session = (COURSE_CODING.Common.InfoLogIn)Session[CommonProject.CommonConstant.SESSION_INFO_LOGIN];
            if (session != null)
            {
                return session.ID;
            }
            else
            {
                return -1; 
            }
        }

        [Route("Challenge/{id}/forum")]
        [Route("Compete/{competeID}/Challenge/{id}/forum")]
        public ActionResult Discussion(int id, int? competeID)
        {
            var models = new CommentListModel();


            models.Info = (new UserDAO().GetUserById(GetLoginID()));

            models.challenge = (new ChallengeDAO().GetOne(id));

            models.like_status = (new LikeStatusDAO().GetAllByUser(GetLoginID()));

            var commentList = (new CommentDAO().GetAllByChallenge(id,2));
            if(commentList.Count > 0)
            {
                for (int i = 0; i < commentList.Count; i++)
                {
                    var model = new CommentModel();
                    model.comment = commentList[i];
                    model.owner = (new UserDAO().GetUserById(model.comment.OwnerID));

                    var replyList = (new ReplyDAO().GetAllByComment(model.comment.ID));
                    if (replyList.Count > 0)
                    {
                        for (int j = 0; j < replyList.Count; j++)
                        {
                            var reply = new ReplyModel();
                            reply.reply = replyList[j];
                            reply.owner = (new UserDAO().GetUserById(reply.reply.OwnerID));

                            model.replies.Add(reply);
                        }
                    }

                    models.comments.Add(model);
                }
            }
            ViewBag.competeID = competeID;
            return View(models);
        }

        [HttpPost]
        public ActionResult AddComment(int userID,int challengeID,string commentInput)
        {
            if(ModelState.IsValid)
            {
                var commentDAO = new CommentDAO();
                COMMENT c = new COMMENT();
                c.Text = commentInput;
                c.Likes = 0;
                c.OwnerID = userID;
                c.ChallengeID = challengeID;
                c.CreateDate = DateTime.Now;
                Boolean result = commentDAO.Insert(c);
                if(result)
                {
                    c = commentDAO.GetNewest();
                    return Json(c.ID);
                }
                else
                {
                    ModelState.AddModelError(String.Empty, "Fail to add comment");
                }
            }
            return View("Discussion");
        }

        [HttpPost]
        public ActionResult AddReply(int userID, int commentID, string commentInput)
        {
            if (ModelState.IsValid)
            {
                var replyDAO = new ReplyDAO();
                REPLY c = new REPLY();
                c.Text = commentInput;
                c.Likes = 0;
                c.OwnerID = userID;
                c.CommentID = commentID;
                c.CreateDate = DateTime.Now;
                Boolean result = replyDAO.Insert(c);
                if (result)
                {
                    c = replyDAO.GetNewest();
                    return Json(c.ID);
                }
                else
                {
                    ModelState.AddModelError(String.Empty, "Fail to add comment");
                }
            }
            return View("Discussion");
        }

        [HttpPost]
        public ActionResult UpdateLikes(int likes,int commentId, int userId, string type)
        {
            if(ModelState.IsValid)
            {
                if(type.Equals("comment"))
                {
                    var commentDAO = new CommentDAO();
                    var statusDAO = new LikeStatusDAO();
                    COMMENT c = commentDAO.GetOne(commentId);

                    LIKE_STATUS s = new LIKE_STATUS();

ProjectMVC/COURSE_CODING/Views/Challenge/Edit.cshtml
@using COURSE_CODING.Models
@model COURSE_CODING.Models.EditDetailModel

@{
    ViewBag.Title = "Edit Challenge";
    Layout = "~/Views/Shared/_User_Layout.cshtml";
}

@if (ViewBag.CanAccess == false)
{
    <div style="text-align: center;margin: 0 auto; padding: 30px;">
        <h2>You don't have permission to view this page</h2>
        <h2>405!</h2>
    </div>
    return;
}

@section CustomCSS
{
    @Styles.Render("~/Assets/Public/css/EditChallenge.css")
    <link href="https://fonts.googleapis.com/css?family=Roboto:400,700" rel="stylesheet">
}

<script src="~/Scripts/jquery-1.10.2.min.js"></script>
<script src="~/Scripts/jquery.unobtrusive-ajax.js"></script>

<div style="border-bottom: 1px solid #C2C7D0;">
    <div class="container">
        <nav aria-label="breadcrumb">
            <ol class="breadcrumb">
                <li class="breadcrumb-item">
                    <a href="/Moderator/ManageChallenge"><b>Moderator Management</b></a>
                </li>

                <li class="breadcrumb-item active">
                    <a href="#"><b>@ViewBag.Name</b></a>
                </li>
            </ol>
        </nav>
    </div>
</div>

<section class="content-page edit-challenge">
    <div class="container">
        <h1 class="title">@ViewBag.Name</h1>
        <nav class="navbar navbar-light bg-light">
            <ul class="nav nav-tabs tabs-bar" style="margin-bottom: 0;">
                <li class="nav-item">
                    <a id="js-details" class="nav-link active" href="/Moderator/Edit/Challenge/@Model.ID">Details</a>
                </li>
                <li class="nav-item"><a id="js-moderators" class="nav-link" href="/Moderator/Edit/Challenge/@Model.ID/Moderator">Moderators</a></li>
                <li class="nav-item"><a id="js-test-cases" class="nav-link" href="/Moderator/Edit/Challenge/@Model.ID/Testcase">Test cases</a></li>
                <li class="nav-item"><a id="js-code-stubs" class="nav-link" href="/Moderator/Edit/Challenge/@Model.ID/Codestubs">Code stubs</a></li>
                <li class="nav-item"><a id="js-languages" class="nav-link" href="/Moderator/Edit/Challenge/@Model.ID/Languages">Languages</a></li>
                <li class="nav-item"><a id="js-settings" class="nav-link" href="/Moderator/Edit/Challenge/@Model.ID/Settings">Settings</a></li>
            </ul>
        </nav>


        <div class="details-modal main-modal" id="div-details-modal">
            <div class="clearfix" style="padding-bottom: 15px;">
                <div style="float: left;">
                    This is the basic infomation that describes your challenge.
                </div>
                <!-- <a class="btn btn-success" href="#" style="float: right;">Create Contest</a> -->
            </div>

            @using (Ajax.BeginForm("UpdateDetails", "Challenge", new AjaxOptions()
            {
                HttpMethod = "POST",
                OnSuccess = "OnSuccessDetail",
                OnFailure = "OnFailure"
            }, new { @class = "form-horizontal" }))
            {
                @Html.Hidden("ID", Model.ID)
                <div class="form-group row">
                    <label class="col-sm-2 control-label" for="language_Input">Language</label>
                    <div class="col-sm-3">
                        @Html.DropDownListFor(model => model.Language,
                                            new SelectList(Enum.GetValues(typeof(Language))),
                                            new { @class = "form-control", @id = "language_Input" })
                        @*<select class="form-control" id="language_Input">
                                <option>English</option>
                                <option>Vietnamese</option>
                            </select>*@
                    </div>
                </div>
                <div class="form-group row">
                    <label class="col-sm-2 control-label" for="difficulty_Input">Challenge Difficulty</label>
                    <div class="col-sm-3">
                        @Html.DropDownListFor(model => model.Difficulty,
                                            new SelectList(Enum.GetValues(typeof(Difficulty))),
                                            new { @class = "form-control", @id = "difficulty_Input" })
                        @*<select class="form-control" id="difficulty_Input">
                                <option>Easy</option>
                                <option>Medium</option>
                                <option>Hard</option>
                                <option>Advanced</option>
                                <option>Expert</option>
                            </select>*@
                    </div>
                </div>
                <div class="form-group row">
                    <label class="col-sm-2 control-label" for="name_Input">Challenge Name</label>
                    <div class="col-sm-8">
                        @Html.TextBoxFor(model => model.Name, new { @class = "form-control", @id = "name_Input" })
                        @*<input class="form-control" id="name_Input" type="text">*@
                    </div>
                </div>
                <div class="form-group row">
                    <label class="col-sm-2 control-label" for="slug_Input">Challenge Slug</label>
                    <div class="col-sm-8">
                        <p class="form-control-static" id="slug_Input">https://www.khtnfitk15.somee.com/.../@Html.DisplayFor(model => model.Slug)</p>
                    </div>
                </div>
                <div class="form-group row">
                    <label class="col-sm-2 control-label" for="description_Input">Score</label>
                    <div class="col-sm-8">
                        @Html.TextBoxFor(model => model.Score, new { @class = "form-control", @id = "score_Input", style = "width: 250px", type = "number" })
                        @*<textarea class="form-control" rows="2" id="description_Input"></textarea>*@
                    </div>
                </div>
                <div class="form-group row">
                    <label class="col-sm-2 control-label" for="description_Input">Description</label>
                    <div class="col-sm-8">
                        @Html.TextAreaFor(model => model.Description, new { @class = "form-control", @id = "description_Input", @rows = "4" })
                        @*<textarea class="form-control" rows="2" id="description_Input"></textarea>*@
                    </div>
                </div>
                <div class="form-group row">
                    <label class="col-sm-2 control-label" for="problem_Input">Problem Statement</label>
                    <div class="col-sm-8">
                        @Html.TextAreaFor(model => model.ProblemStatement, new { @class = "form-control", @id = "problem_Input", @rows = "4" })
                        @*<textarea class="form-control" rows="2" id="problem_Input"></textarea>*@
                    </div>
                </div>
                <div class="form-group row">
                    <label class="col-sm-2 control-label" for="inputFormat_Input">Input Format</label>
                    <div class="col-sm-8">
                        @Html.TextAreaFor(model => model.InputFormat, new { @class = "form-control", @id = "inputFormat_Input", @rows = "4" })
                        @*<textarea class="form-control" rows="2" id="inputFormat_Input"></textarea>*@
                    </div>
                </div>
                <div class="form-group row">
                    <label class="col-sm-2 control-label" for="constraints_Input">Constraints</label>
                    <div class="col-sm-8">
                        @Html.TextAreaFor(model => model.Constraints, new { @class = "form-control", @id = "constraints_Input", @rows = "4" })
                        @*<textarea class="form-control" rows="2" id="constraints_Input"></textarea>*@
                    </div>
                </div>
                <div class="form-group row">
                    <label class="col-sm-2 control-label" for="outputFormat_Input">Output Format</label>
                    <div class="col-sm-8">
                        @Html.TextAreaFor(model => model.OutputFormat, new { @class = "form-control", @id = "outputFormat_Input", @rows = "4" })
                        @*<textarea class="form-control" rows="2" id="outputFormat_Input"></textarea>*@
                    </div>
                </div>
                <div class="form-group row">
                    <label class="col-sm-2 control-label" for="tags_Input">Tags</label>
                    <div class="col-sm-8">
                        @Html.TextAreaFor(model => model.Tags, new { @class = "form-control", @id = "tags_Input", @rows = "4" })
                        @*<textarea class="form-control" rows="2" id="tags_Input"></textarea>*@
                    </div>
                </div>
                <div class="save-change-btn-group">
                    <button class="btn btn-success" id="js-save-changes-btn" type="submit">Save Changes</button>
                </div>
            }
            @*<form class="form-horizontal" method="post">

                </form>*@
        </div>
        <div style="height: 100px;">

        </div>
        @*<div class="save-change-btn-group">
                <button class="btn btn-success" id="js-save-changes-btn">Save Changes</button>
            </div>*@
    </div>
</section>

@section scripts
    {
    <script src="~/Assets/Public/vendor/ckeditor5-build-classic/ckeditor.js"></script>
    <script src="~/Assets/Public/vendor/sweetalert2-8.13.1/dist/sweetalert2.all.min.js"></script>
    <script type="text/javascript">

        window.onload = function SetClassicEditor() {
            ClassicEditor
                .create(document.querySelector('#description_Input'))
                .catch(error => {
                    console.error(error);
                });
            ClassicEditor
                .create(document.querySelector('#problem_Input'))
                .catch(error => {
                    console.error(error);
                });
            ClassicEditor
                .create(document.querySelector('#inputFormat_Input'))
                .catch(error => {
                    console.error(error);
                });
            ClassicEditor
                .create(document.querySelector('#constraints_Input'))
                .catch(error => {
                    console.error(error);
                });
            ClassicEditor
                .create(document.querySelector('#outputFormat_Input'))
                .catch(error => {
                    console.error(error);
                });
        }

        function OnSuccessDetail(data) {
            if (data.result) {
                document.getElementById("slug_Input").innerHTML = 'https://www.khtnfitk15.somee.com/.../' + data.Slug;
                Swal.fire({
                    position: 'top-end',
                    type: 'success',
                    title: 'Save changes succeed',
                    showConfirmButton: false,
                    timer: 2000
                })
            } else {
                Swal.fire({
                    position: 'top-end',
                    type: 'error',
                    title: 'Save changes fail',
                    showConfirmButton: false,
                    timer: 2000
                })
            }
        }
        function OnFailure(data) {
            Swal.fire({
                position: 'top-end',
                type: 'error',
                title: 'POST: fail',
                showConfirmButton: false,
                timer: 2000
            })
        }
    </script>
}

ProjectMVC/COURSE_CODING/Views/Challenge/EditLanguages.cshtml
@using COURSE_CODING.Models
@model COURSE_CODING.Models.EditLanguagesModel

@{
    ViewBag.Title = "Edit Challenge";
    Layout = "~/Views/Shared/_User_Layout.cshtml";
}

@if (ViewBag.CanAccess == false)
{
    <div style="text-align: center;margin: 0 auto; padding: 30px;">
        <h2>You don't have permission to view this page</h2>
        <h2>405!</h2>
    </div>
    return;
}

@section CustomCSS
{
    @Styles.Render("~/Assets/Public/css/EditChallenge.css")
    <link href="https://fonts.googleapis.com/css?family=Roboto:400,700" rel="stylesheet">
}

<script src="~/Scripts/jquery-1.10.2.min.js"></script>
<script src="~/Scripts/jquery.unobtrusive-ajax.js"></script>

<div style="border-bottom: 1px solid #C2C7D0;">
    <div class="container">
        <nav aria-label="breadcrumb">
            <ol class="breadcrumb">
                <li class="breadcrumb-item">
                    <a href="/Moderator/ManageChallenge"><b>Moderator Management</b></a>
                </li>

                <li class="breadcrumb-item active">
                    <a href="#"><b>@ViewBag.Name</b></a>
                </li>
            </ol>
        </nav>
    </div>
</div>

<section class="content-page edit-challenge">
    <div class="container">
        <h1 class="title">@ViewBag.Name</h1>
        <nav class="navbar navbar-light bg-light">
            <ul class="nav nav-tabs tabs-bar" style="margin-bottom: 0;">
                <li class="nav-item">
                    <a id="js-details" class="nav-link" href="/Moderator/Edit/Challenge/@Model.ID">Details</a>
                </li>
                <li class="nav-item"><a id="js-moderators" class="nav-link" href="/Moderator/Edit/Challenge/@Model.ID/Moderator">Moderators</a></li>
                <li class="nav-item"><a id="js-test-cases" class="nav-link" href="/Moderator/Edit/Challenge/@Model.ID/Testcase">Test cases</a></li>
                <li class="nav-item"><a id="js-code-stubs" class="nav-link" href="/Moderator/Edit/Challenge/@Model.ID/Codestubs">Code stubs</a></li>
                <li class="nav-item"><a id="js-languages" class="nav-link active" href="/Moderator/Edit/Challenge/@Model.ID/Languages">Languages</a></li>
                <li class="nav-item"><a id="js-settings" class="nav-link" href="/Moderator/Edit/Challenge/@Model.ID/Settings">Settings</a></li>
            </ul>
        </nav>

        <div class="languages-modal main-modal" id="div-languages-modal">
            <div class="clearfix">
                <p>Select the enviroment for available languages and libraries.</p>
            </div>
            @using (Ajax.BeginForm("UpdateLanguages", "Challenge", new AjaxOptions()
            {
                HttpMethod = "POST",
                OnSuccess = "OnSuccess",
                OnFailure = "OnFailure"
            }, new { @class = "form-horizontal" }))
            {
                @Html.Hidden("ID", Model.ID)
                <table class="table">
                    <thead>
                        <tr>
                            <th>Language</th>
                            <th></th>
                        </tr>
                    </thead>
                    <tbody>
                        <tr>
                            <td>C#</td>
                            <td>@Html.CheckBoxFor(model => model.LanguageCSharp, new { @id = "language_csharp_checkbox" })@*<input type="checkbox" id="language_csharp_checkbox" value="">*@</td>
                        </tr>
                        <tr>
                            <td>C++</td>
                            <td>@Html.CheckBoxFor(model => model.LanguageCpp, new { @id = "language_cpp_checkbox" })@*<input type="checkbox" id="language_cpp_checkbox" value="">*@</td>
                        </tr>
                        <tr>
                            <td>Java</td>
                            <td>@Html.CheckBoxFor(model => model.LanguageJava, new { @id = "language_java_checkbox" })@*<input type="checkbox" id="language_java_checkbox" value="">*@</td>
                        </tr>
                    </tbody>
                </table>
                <div class="save-change-btn-group">
                    <button class="btn btn-success" id="js-save-changes-btn" type="submit">Save Changes</button>
                </div>
            }
        </div>
        <div style="height: 100px;">

        </div>
        @*<div class="save-change-btn-group">
                <button class="btn btn-success" id="js-save-changes-btn">Save Changes</button>
            </div>*@
    </div>
</section>

@section scripts
    {
    <script src="~/Assets/Public/vendor/sweetalert2-8.13.1/dist/sweetalert2.all.min.js"></script>
    <script type="text/javascript">
        function OnSuccess(data) {
            if (data.result) {
                Swal.fire({
                    position: 'top-end',
                    type: 'success',
                    title: 'Save changes succeed',
                    showConfirmButton: false,
                    timer: 2000
                })
            } else {
                Swal.fire({
                    position: 'top-end',
                    type: 'error',
                    title: 'Error',
                    text: data.msg,
                    showConfirmButton: false,
                    timer: 2000
                })
            }
        }

        function OnFailure(data) {
            Swal.fire({
                position: 'top-end',
                type: 'error',
                title: 'POST: fail',
                showConfirmButton: false,
                timer: 2000
            })
        }
    </script>
}