ProjectMVC/COURSE_CODING/Controllers/AuthenController.cs
using System;
using System.Collections.Generic;
using System.Configuration;
using System.Linq;
using System.Security.Claims;
using System.Web;
using System.Web.Mvc;
using System.Web.Security;
using BotDetect.Web.Mvc;
using CommonProject;
using CommonProject.Helper;
using COURSE_CODING.Common;
using COURSE_CODING.Models;
using DAO.DAO;
using DAO.EF;
using Microsoft.Owin.Security;
using Microsoft.Owin.Security.Cookies;

namespace COURSE_CODING.Controllers
{
    public class AuthenController : Controller
    {
        //[OutputCache(Duration = 3600, VaryByParam = "none")]
        private string stringOTP = string.Empty;
        private DateTime timeBegin;

        [HttpGet]
        public ActionResult Home()
        {
            var session = (COURSE_CODING.Common.InfoLogIn)Session[CommonProject.CommonConstant.SESSION_INFO_LOGIN];
            if (session != null)
            {
                if (session.Role.Equals(CommonConstant.ROLE_ADMIN))
                {
                    return Redirect("/Admin/User/index");
                }
                else
                {
                    if (session.Role.Equals(CommonConstant.ROLE_MEMBER))
                    {
                        return Redirect("/User/Dashboard");
                    }
                }
                if (session.Role.Equals(CommonConstant.ROLE_TEACHER))
                {
                    return Redirect("/Moderator/ManageChallenge");
                }
            }
            return View("Login");
        }
        [HttpGet]
        public ActionResult Register()
        {
            var session = (COURSE_CODING.Common.InfoLogIn)Session[CommonProject.CommonConstant.SESSION_INFO_LOGIN];
            if (session != null)
            {
                if (session.Role.Equals(CommonConstant.ROLE_ADMIN))
                {
                    return Redirect("/Admin/User/index");
                }
                else
                {
                    if (session.Role.Equals(CommonConstant.ROLE_MEMBER))
                    {
                        return Redirect("/User/Dashboard");
                    }
                }
                if (session.Role.Equals(CommonConstant.ROLE_TEACHER))
                {
                    return Redirect("/Moderator/ManageChallenge");
                }

            }
            return View();
        }

        [HttpPost]
        [AllowAnonymous]
        [CaptchaValidation("CaptchaCode", "registerCaptcha", "Incorrect CAPTCHA code!")]
        public ActionResult Register(RegisterModel model)
        {
            if (ModelState.IsValid)
            {
                string callback_uri = string.Empty;
                if (Request.UrlReferrer != null)
                {
                    var paramss = HttpUtility.ParseQueryString(Request.UrlReferrer.Query);
                    callback_uri = paramss["callback"] ?? "";
                }
                var DAO = new UserDAO();
                if (DAO.CheckUserNameExist(model.UserName))
                {
                    ModelState.AddModelError(String.Empty, "This user name is existed");
                }
                else if (DAO.CheckEmailExist(model.Email))
                {
                    ModelState.AddModelError(String.Empty, "Your email is registerd");
                }
                else
                {
                    USER_INFO u = new USER_INFO();
                    u.FirstName = model.FirstName;
                    u.LastName = model.LastName;
                    u.UserName = model.UserName;
                    u.PasswordUser = HashMD5.HashStringMD5(model.PasswordUser);
                    u.RoleUser = CommonConstant.ROLE_MEMBER;
                    u.Email = model.Email;
                    u.SchoolID = 1;
                    u.CreateDate = DateTime.Now;
                    Boolean result = DAO.Insert(u);
                    if (result)
                    {
                        var sessionLogin = new InfoLogIn();
                        sessionLogin.ID = u.ID;
                        sessionLogin.Name = u.UserName;
                        Session.Add(CommonConstant.SESSION_INFO_LOGIN, sessionLogin);
                        ViewBag.Success = "Register sussesfull";
                        model = new RegisterModel();
                        if (!String.IsNullOrEmpty(callback_uri))
                        {
                            return Redirect(callback_uri);
                        }
                        return Redirect("/User/Dashboard");
                    }
                    else
                    {
                        ModelState.AddModelError(String.Empty, "Fail register your account");
                    }
                }
            }
            return View("Register");
        }

        [OutputCache(Duration = 3600, VaryByParam = "none")]
        [HttpGet]
        public ActionResult Login()
        {
            var session = (COURSE_CODING.Common.InfoLogIn)Session[CommonProject.CommonConstant.SESSION_INFO_LOGIN];
            if (session != null)
            {
                if (session.Role.Equals(CommonConstant.ROLE_ADMIN))
                {
                    return Redirect("/Admin/User/index");
                }
                else
                {
                    if (session.Role.Equals(CommonConstant.ROLE_MEMBER))
                    {
                        return Redirect("/User/Dashboard");
                    }
                }
                if (session.Role.Equals(CommonConstant.ROLE_TEACHER))
                {
                    return Redirect("/Moderator/ManageChallenge");
                }

            }

            return View();
        }

        public ActionResult Logout()
        {
            Session[CommonConstant.SESSION_INFO_LOGIN] = null;
            HttpContext.GetOwinContext().Authentication.SignOut(CookieAuthenticationDefaults.AuthenticationType);
            return Redirect("/");
        }

        [HttpPost]
        public ActionResult Login(LoginModel model)
        {
            if (ModelState.IsValid)
            {
                string callback_uri = string.Empty;
                if (Request.UrlReferrer != null)
                {
                    var paramss = HttpUtility.ParseQueryString(Request.UrlReferrer.Query);
                    callback_uri = paramss["callback"] ?? "";
                }
                var DAO = new UserDAO();
                var statusLogin = DAO.Login(model.UserName, HashMD5.HashStringMD5(model.Password));
                if (statusLogin.Equals(CommonConstant.STATUS_RIGHT_ACCOUNT))
                {
                    var user = DAO.GetByName(model.UserName);
                    var sessionLogin = new InfoLogIn();
                    sessionLogin.ID = user.ID;
                    sessionLogin.Name = user.UserName;
                    sessionLogin.Role = (int)user.RoleUser;
                    Session.Add(CommonConstant.SESSION_INFO_LOGIN, sessionLogin);

                    if (!String.IsNullOrEmpty(callback_uri))
                    {
                        return Redirect(callback_uri);
                    }
                    if (user.RoleUser.Equals(CommonConstant.ROLE_ADMIN))
                    {
                        return Redirect("/Admin/Home/Index");
                    }
                    else if (user.RoleUser.Equals(CommonConstant.ROLE_MEMBER))
                    {
                        return Redirect("/User/Dashboard");
                    }
                    else if (user.RoleUser.Equals(CommonConstant.ROLE_TEACHER))
                    {
                        return Redirect("/Moderator/ManageChallenge");
                    }
                    return Redirect("/");
                }
                else if (statusLogin.Equals(CommonConstant.STATUS_NOT_EXIST_ACCOUNT))
                {
                    ModelState.AddModelError(String.Empty, "This account is not exist");
                }
                else if (statusLogin.Equals(CommonConstant.STATUS_LOCK_ACCOUNT))
                {
                    ModelState.AddModelError(String.Empty, "This account is locked");
                }
                else if (statusLogin.Equals(CommonConstant.STATUS_WRONG_PASS_ACCOUNT))
                {
                    ModelState.AddModelError(String.Empty, "Your password is wrong");
                }
                else
                {
                    ModelState.AddModelError(String.Empty, "Fail login !");
                }
            }
            else
            {
                MvcCaptcha.ResetCaptcha("registerCaptcha");
            }
            return View();
        }
        public void SignIn(string ReturnUrl = "/", string type = "")
        {
            try
            {
                if (type == "Google")
                {
                    HttpContext.GetOwinContext().Authentication.Challenge(new
                        AuthenticationProperties
                    { RedirectUri = "Authen/GoogleLoginCallback" }, "Google");
                }
            }
            catch(Exception ex)
            {

            }
            
        }

        [AllowAnonymous]
        public ActionResult GoogleLoginCallback()
        {
            try
            {
                var claimsPrincipal = HttpContext.User.Identity as ClaimsIdentity;
                var loginInfo = GoogleLoginViewModel.GetLoginInfo(claimsPrincipal);
                if (loginInfo == null)
                {
                    return RedirectToAction("/");
                }
                string callback_uri = string.Empty;
                if (Request.UrlReferrer != null)
                {
                    var paramss = HttpUtility.ParseQueryString(Request.UrlReferrer.Query);
                    callback_uri = paramss["callback"] ?? "";
                }
                var DAO = new UserDAO();
                var user = DAO.GetByEmail(loginInfo.emailaddress);

ProjectMVC/COURSE_CODING/Views/Authen/ChangePassword.cshtml
@model COURSE_CODING.Models.ForgotPasswordModel

@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Login</title>
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.8.1/css/all.css" integrity="sha384-50oBUHEmvpQ+1lW4y57PTFmhCaXp0ML5d60M1M7uH2+nqUivzIebhndOJK28anvf" crossorigin="anonymous">
    @Styles.Render("~/Content/cssRegister")
</head>
<body class="bgForm">

    <div class="container">
        <div class="card card-register mx-auto mt-5">
            <h1 class="card-header justify-content-center align-center text-center">Change password</h1>
            <div class="card-body">
                @using (Html.BeginForm("ChangePassword", "Authen", FormMethod.Post))
                {
                <div class="form-horizontal">
                    <div>
                        @if (ViewBag.Success != null)
        {<div class="alert alert-success">@ViewBag.Success</div>}
else
{
}
                    </div>
                    <div id="status_view">
                        @if (TempData["AlertMessage"] != null)
        {
                <div id="AlertBox" class="alert @TempData["AlertType"] hide">
                    @TempData["AlertMessage"]
                </div>
}
                    </div>
                    <div class="form-group">
                        <div class="form-row">
                            @Html.LabelFor(model => model.Email, htmlAttributes: new { @class = "control-label col-md-3 pt-1" })
                            <div class="col-md-9">
                                @Html.EditorFor(model => model.Email, new { htmlAttributes = new { @class = "form-control" } })
                                @Html.ValidationMessageFor(model => model.Email, "", new { @class = "text-danger" })
                            </div>
                        </div>
                    </div>

                    @if (ViewBag.isValidateCode != false)
    {
                <div class="form-group">
                    <div class="form-row">
                        @Html.LabelFor(model => model.CodeValidate, htmlAttributes: new { @class = "control-label col-md-3 pt-1" })
                        <div class="col-md-9">
                            @Html.EditorFor(model => model.CodeValidate, new { htmlAttributes = new { @class = "form-control" } })
                            @Html.ValidationMessageFor(model => model.CodeValidate, "", new { @class = "text-danger" })
                        </div>
                    </div>
                </div>
}


                    <div class="form-group">
                        <div class="form-row">
                            @Html.LabelFor(model => model.Password, htmlAttributes: new { @class = "control-label col-md-3 pt-1" })
                            <div class="col-md-9">
                                @Html.EditorFor(model => model.Password, new { htmlAttributes = new { @class = "form-control" } })
                                @Html.ValidationMessageFor(model => model.Password, "", new { @class = "text-danger" })
                            </div>
                        </div>
                    </div>
                    <div class="form-group">
                        <div class="form-row">
                            @Html.LabelFor(model => model.ComfirmPassword, htmlAttributes: new { @class = "control-label col-md-3 pt-1" })
                            <div class="col-md-9">
                                @Html.EditorFor(model => model.ComfirmPassword, new { htmlAttributes = new { @class = "form-control" } })
                                @Html.ValidationMessageFor(model => model.ComfirmPassword, "", new { @class = "text-danger" })
                            </div>
                        </div>
                    </div>
                    <div class="form-group">
                        <div class="form-row">
                            <div class="col-md-12 offset-3">
                                <input type="submit" value="Change" class="btn btn-success" />
                            </div>
                        </div>
                    </div>

                </div>
                }
            </div>
        </div>
    </div>
    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/jqueryval")
</body>
</html>

ProjectMVC/COURSE_CODING/Views/Authen/ForgotPassword.cshtml
@model COURSE_CODING.Models.ResetModel

@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Login</title>
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.8.1/css/all.css" integrity="sha384-50oBUHEmvpQ+1lW4y57PTFmhCaXp0ML5d60M1M7uH2+nqUivzIebhndOJK28anvf" crossorigin="anonymous">
    @Styles.Render("~/Content/cssRegister")
</head>
<body class="bgForm">
    <div class="container">
        <div class="card card-login mx-auto mt-5">
            <h3 class="card-header">Reset Password</h3>
            <div class="card-body">
                <div class="text-center mb-4">
                    <h4>Forgot your password?</h4>
                    <p>Enter your email address and we will send you instructions on how to reset your password.</p>
                </div>
                    @using (Html.BeginForm("ForgotPassword", "Authen", FormMethod.Post))
    {
                <div class="form-horizontal">

                    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                    <div class="form-group mb-5">
                        <div class="form-row">
                            @Html.LabelFor(model => model.Email, htmlAttributes: new { @class = "control-label col-md-2 pt-1", @style = "text-align:left" })
                            <div class="col-md-10">
                                @Html.EditorFor(model => model.Email, new { htmlAttributes = new { @class = "form-control" } })
                                @Html.ValidationMessageFor(model => model.Email, "", new { @class = "text-danger" })
                            </div>
                        </div>
                    </div>
                    <div class="form-group mt-5">
                        <div class="form-row">
                            <div class="col-md-12">
                                <input type="submit" value="Reset Password" class="btn btn-lg btn-success btn-block" />
                            </div>

                        </div>
                    </div>

                </div>
}
                <div class="text-center">
                    <a class="d-block small mt-3" href="../Register">Register</a>
                    <a class="d-block small" href="../login">Login</a>
                </div>
            </div>
        </div>
    </div>
    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/jqueryval")
</body>
</html>

ProjectMVC/COURSE_CODING/Views/Authen/Login.cshtml
@model COURSE_CODING.Models.LoginModel

@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Login</title>
    @*<!-- Bootstrap Core CSS -->
    <link href="/Assets/Page/vendor/bootstrap/css/bootstrap.min.css" rel="stylesheet">
    <!-- Custom CSS -->
    <link href="/Assets/Page/dist/css/sb-admin-2.css" rel="stylesheet">*@
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.8.1/css/all.css" integrity="sha384-50oBUHEmvpQ+1lW4y57PTFmhCaXp0ML5d60M1M7uH2+nqUivzIebhndOJK28anvf" crossorigin="anonymous">
    @Styles.Render("~/Content/cssLogin")
</head>
<body class="bgForm">
    <div class="container">
        <div class="row">
            <div class="col-md-4 col-md-offset-4 ">
                <div class="login-panel panel panel-default">
                    <div class="panel-heading">
                        <h1 class="panel-title">Please log in</h1>
                    </div>
                    <div class="panel-body">

                        @using (Html.BeginForm("Login", "Authen", FormMethod.Post))
                        {
                            @*@Html.AntiForgeryToken()*@

                        <div class="form-horizontal">

                            @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                            <div class="form-group mb-5">
                                <div class="form-row">
                                    @Html.LabelFor(model => model.UserName, htmlAttributes: new { @class = "control-label col-md-4", @style = "text-align:left" })
                                    <div class="col-md-8">
                                        @Html.EditorFor(model => model.UserName, new { htmlAttributes = new { @class = "form-control" } })
                                        @Html.ValidationMessageFor(model => model.UserName, "", new { @class = "text-danger" })
                                    </div>
                                </div>
                            </div>
                            <div class="form-group mb-5">
                                <div class="form-row">
                                    @Html.LabelFor(model => model.Password, htmlAttributes: new { @class = "control-label col-md-4", @style = "text-align:left" })
                                    <div class="col-md-8">
                                        @Html.EditorFor(model => model.Password, new { htmlAttributes = new { @class = "form-control" } })
                                        @Html.ValidationMessageFor(model => model.Password, "", new { @class = "text-danger" })
                                    </div>
                                </div>
                            </div>

                            <div class="form-group mt-5">
                                <div class="form-row">
                                    <div class="col-md-12">
                                        <input type="submit" value="Login" class="btn btn-lg btn-success btn-block" />
                                    </div>

                                </div>
                            </div>
                            <div class="form-group">
                                <div class="form-row mt-5">
                                    <div class="col-md-12">
                                        <a style="color:white" class="btn btn-block btn-social btn-lg btn-google-plus btn-danger" href="@Url.Action("SignIn","Authen", new { type = "Google" })"><i class="fab fa-google"></i>&nbsp;&nbsp;Login Google</a>
                                    </div>
                                </div>
                            </div>

                            <div class="form-group">
                                <div class="form-row mt-5">
                                    <div class="col-md-12">
                                        <a class="btn btn-lg btn-primary btn-block" href="/Register">
                                            <i class="fab  primary"></i>
                                            Or register now
                                        </a>
                                    </div>
                                </div>
                            </div>
                            <div class="text-center">
                                <a class="d-block small mt-3" href="/Forgotpassword">Forgot password</a>
                            </div>
                        </div>
                        }
                    </div>
                </div>
            </div>
        </div>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/jqueryval")

</body>
</html>

ProjectMVC/COURSE_CODING/Views/Authen/Register.cshtml
@model COURSE_CODING.Models.RegisterModel
@using BotDetect.Web.Mvc
<link href="@BotDetect.Web.CaptchaUrls.Absolute.LayoutStyleSheetUrl"
      rel="stylesheet" type="text/css" />
@{
    Layout = null;
}
@{ MvcCaptcha registerCaptcha = new MvcCaptcha("registerCaptcha"); }
<!DOCTYPE html>

<html>
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>Register</title>
    <!-- Bootstrap core CSS-->
    @*<link href="/Assets/Page/vendor/bootstrap/css/bootstrap.min1.css" rel="stylesheet">*@
    <!-- Custom styles for this template-->
    @*<link href="/Assets/Page/dist/css/sb-admin.css" rel="stylesheet">*@
    @Styles.Render("~/Content/cssRegister")
</head>
<body class="bgForm">

    <div class="container">
        <div class="card card-register mx-auto mt-5">
            <h1 class="card-header justify-content-center align-center text-center">Register an Account</h1>
            <div class="card-body">
                @using (Html.BeginForm("Register", "Authen", FormMethod.Post))
                {
                    @*@Html.AntiForgeryToken()*@

                    <div class="form-horizontal">
                        <div>
                            @if (ViewBag.Success != null)
                            {<div class="alert alert-success">@ViewBag.Success</div>}
                        else
                        {
                            @*<h4>Register now</h4>*@
                        }
                        </div>
                        @*<hr />*@
                        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                        <div class="form-group ">
                            <div class="form-row">
                                @Html.LabelFor(model => model.UserName, htmlAttributes: new { @class = "control-label col-md-3 align-middle pt-1" })
                                <div class="col-md-9">
                                    @Html.EditorFor(model => model.UserName, new { htmlAttributes = new { @class = "form-control" } })
                                    @Html.ValidationMessageFor(model => model.UserName, "", new { @class = "text-danger" })
                                </div>
                            </div>

                        </div>
                        <div class="form-group">
                            <div class="form-row">
                                @Html.LabelFor(model => model.FirstName, htmlAttributes: new { @class = "control-label col-md-3 pt-1" })
                                <div class="col-md-9">
                                    @Html.EditorFor(model => model.FirstName, new { htmlAttributes = new { @class = "form-control" } })
                                    @Html.ValidationMessageFor(model => model.FirstName, "", new { @class = "text-danger" })
                                </div>
                            </div>
                        </div>
                        <div class="form-group">
                            <div class="form-row">
                                @Html.LabelFor(model => model.LastName, htmlAttributes: new { @class = "control-label col-md-3 pt-1" })
                                <div class="col-md-9">
                                    @Html.EditorFor(model => model.LastName, new { htmlAttributes = new { @class = "form-control" } })
                                    @Html.ValidationMessageFor(model => model.LastName, "", new { @class = "text-danger" })
                                </div>
                            </div>
                        </div>
                        <div class="form-group">
                            <div class="form-row">
                                @Html.LabelFor(model => model.Email, htmlAttributes: new { @class = "control-label col-md-3 pt-1" })
                                <div class="col-md-9">
                                    @Html.EditorFor(model => model.Email, new { htmlAttributes = new { @class = "form-control" } })
                                    @Html.ValidationMessageFor(model => model.Email, "", new { @class = "text-danger" })
                                </div>

                            </div>

                        </div>
                        <div class="form-group">
                            <div class="form-row">
                                @Html.LabelFor(model => model.PasswordUser, htmlAttributes: new { @class = "control-label col-md-3 pt-1" })
                                <div class="col-md-9">
                                    @Html.EditorFor(model => model.PasswordUser, new { htmlAttributes = new { @class = "form-control" } })
                                    @Html.ValidationMessageFor(model => model.PasswordUser, "", new { @class = "text-danger" })
                                </div>
                            </div>
                        </div>
                        <div class="form-group">
                            <div class="form-row">
                                @Html.LabelFor(model => model.ComfirmPasswordUser, htmlAttributes: new { @class = "control-label col-md-3" })
                                <div class="col-md-9">
                                    @Html.EditorFor(model => model.ComfirmPasswordUser, new { htmlAttributes = new { @class = "form-control" } })
                                    @Html.ValidationMessageFor(model => model.ComfirmPasswordUser, "", new { @class = "text-danger" })
                                </div>
                            </div>
                        </div>

                        <div class="form-group">
                            <div class="form-row">
                                <div class="col-md-3 pt-1">

                                </div>

                                <div class="col-md-9">
                                    @Html.Captcha(registerCaptcha)
                                </div>

                            </div>
                            <div class="form-row mt-2">
                                <div class="col-md-3 pt-1">
                                    <label>Fill captcha</label>
                                </div>
                                <div class="col-md-9">
                                    @Html.TextBox("CaptchaCode")
                                </div>
                            </div>
                        </div>
                        <div class="form-group">
                            <div class="form-row">
                                <div class="col-md-12 offset-4">
                                    <input type="submit" value="Register" class="btn btn-success" />
                                    <a class="btn btn-info" style="padding-left:24px;padding-right:24px;margin-left:30px;" href="../">
                                        Back
                                    </a>
                                </div>
                            </div>

                        </div>

                    </div>
                }
                @*<div class="text-center">
                        @Html.ActionLink("forgot-password", "ChangePassword")
                    </div>*@
            </div>
        </div>
    </div>
    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/jqueryval")
</body>
</html>